config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  resources :labs
  resources :students
  root 'labs#index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
  validates :first, presence: true
  validates :rank, presence: true


  VALID_CODE =  /1[34]+TI0[0-9][0-9]/
  validates :code, presence: true, format: {with: VALID_CODE}
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /students
  # GET /students.json
  def index
    @students = Student.all.order(:rank)
  end

  # GET /students/1
  # GET /students/1.json
  def show
    unless current_user.id == 1
      redirect_to :root
    end
  end

  # GET /students/new
  def new
    @labs = Lab.all
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    if current_user.id != 1
      if @student.third != current_user.id
        redirect_to :back
      end
    end
    @labs = Lab.all
  end

  # POST /students
  # POST /students.json
  def create
    @labs = Lab.all
    if Student.find_by third: current_user.id
      return if current_user.id != 1
    end
    @student = Student.new(student_params)
    @student.third = current_user.id
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    @labs = Lab.all
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    if current_user.id == 1 || @student.third == current_user.id
      @student.destroy
      respond_to do |format|
        format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.require(:student).permit(:name, :rank, :first, :second, :third, :code)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label> 名前(表示用 匿名OK)</label>
    <%= f.text_field :name %>
  </div>

    <div class="field">
      <label> 学籍番号(非公開) </label>
      <%= f.text_field :code %>
    </div>

  <div class="field">
    <%= f.label :順位 %>
    <%= f.number_field :rank %>
  </div>

  <div class="field">
    <%= f.label :第1希望 %>
    <select name="student[first]" id="student_first">
      <% @labs.each do |lab| %>
      <option <% if student.first == lab.id %> selected <% end %> value="<%= lab.id %>"><%= lab.name %>研究室</option>
      <% end %>
    </select>
  </div>

  <div class="field">
    <%= f.label :第2希望 %>
        <select name="student[second]" id="student_second">
          <% @labs.each do |lab| %>
          <option <% if student.second == lab.id %> selected <% end %> value="<%= lab.id %>"><%= lab.name %>研究室</option>
          <% end %>
        </select>
  </div>

  <div class="field">
    <%= f.hidden_field :third %>
  </div>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>編集</h1>

<%= render 'form', student: @student %>

<br>
<%= link_to 'もどる', students_path %> 

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>
<div class="student_list">

  <h1>学生情報(順位順)</h1>
  <hr>
    <%= link_to '[ 新規追加 ]', new_student_path %>
    <hr>
  <table>
    <thead>
      <tr>
        <th>名前(匿名)</th>
        <th>順位</th>
        <th>第1希望</th>
        <th>第2希望</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tr><th></th></tr>
    <tbody>
      <% @students.each do |student| %>
      <tr>
        <td><%if current_user.id == 1%>
        <%= student.code  %>
        <% else %>
        <%= student.name  %>
        <% end  %></td>
        <td><%= student.rank %></td>
        <td><%= Lab.find(student.first).name %>研究室</td>
        <td><% if student.second==nil%>未指定<%else%><%= Lab.find(student.second).name %>研究室<%end%></td>
        <% if student.third == current_user.id || current_user.id == 1%>
        <td><%= link_to '[ 編集 ] /', edit_student_path(student) %></td>
        <td><%= link_to '[ 削除 ]', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
    <hr>
      <%= link_to '[ 新規追加 ]', new_student_path %>
      <hr>
</div>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @student.rank %>
</p>

<p>
  <strong>First:</strong>
  <%= @student.first %>
</p>

<p>
  <strong>Second:</strong>
  <%= @student.second %>
</p>

<p>
  <strong>Third:</strong>
  <%= @student.third %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>