config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  resources :labs
  resources :students
  root 'labs#index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lab.rb
class Lab < ApplicationRecord
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
  before_action :set_lab, only: [:show, :edit, :update, :destroy]
  
  # GET /labs
  # GET /labs.json
  def index
    @users = User.all
    @labs = Lab.all
    @codes = Student.all.order("code")
    @students = Student.all.order("rank")
  end

  # GET /labs/1
  # GET /labs/1.json
  def show
        unless current_user.id == 1
          redirect_to :back
        end
  end

  # GET /labs/new
  def new
        unless current_user.id == 1
          redirect_to :back
        end
    @lab = Lab.new
  end

  # GET /labs/1/edit
  def edit
    unless current_user.id == 1
      redirect_to :back
    end
  end

  # POST /labs
  # POST /labs.json
  def create
    if current_user
      @lab = Lab.new(lab_params)

      respond_to do |format|
        if @lab.save
          format.html { redirect_to @lab, notice: 'Lab was successfully created.' }
          format.json { render :show, status: :created, location: @lab }
        else
          format.html { render :new }
          format.json { render json: @lab.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /labs/1
  # PATCH/PUT /labs/1.json
  def update
    if current_user.id==1
      respond_to do |format|
        if @lab.update(lab_params)
          format.html { redirect_to @lab, notice: 'Lab was successfully updated.' }
          format.json { render :show, status: :ok, location: @lab }
        else
          format.html { render :edit }
          format.json { render json: @lab.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /labs/1
  # DELETE /labs/1.json
  def destroy
    if current_user.id==1
      @lab.destroy
      respond_to do |format|
        format.html { redirect_to labs_url, notice: 'Lab was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_lab
    @lab = Lab.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lab_params
    params.require(:lab).permit(:name, :cap, :info)
  end
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/views/labs/_form.html.erb
<%= form_for(lab) do |f| %>
  <% if lab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lab.errors.count, "error") %> prohibited this lab from being saved:</h2>

      <ul>
      <% lab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :cap %>
    <%= f.number_field :cap %>
  </div>

  <div class="field">
    <%= f.label :info %>
    <%= f.text_area :info %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labs/edit.html.erb
<h1>Editing Lab</h1>

<%= render 'form', lab: @lab %>

<%= link_to 'Show', @lab %> |
<%= link_to 'Back', labs_path %>

app/views/labs/index.html.erb
<p id="notice"><%= notice %></p>
<div id="lab">

  <h1>希望研究室情報</h1>
  <hr>

  <div class="lab_list">
    <div class="row">
      <% @labs.each do |lab| %>
      <div class="col-md-4 col-xs-6">
        <div class="lab_detail">
          <h2><%= lab.name %>研究室</h2>
          <h3>配属人数: <%= lab.cap %></h3>
          <p><%= lab.info %></p>
          <table>
            <tr>
              <th>名前(匿名)</th>
              <th class="second">第2希望</th>
              <th>順位</th>
            </tr>
            <% @num = 0 %>
            <% @students.each do |student| %>
            <% if student.first == lab.id %>
            <% @num += 1 %>
            <tr>
              <td>
                <% if @num > lab.cap %>
                <div class="colored">
                  <% end %>
                  <%if current_user.id == 1%>
                  <%= student.code  %>
                  <% else %>
                  <%= student.name  %>
                  <% end  %>
                  <% if @num > lab.cap %>
                </div>
                <% end %>
              </td>
              <td>
                <% if student.second==nil%>未指定<%else%><%= Lab.find(student.second).name %>研究室<%end%>
              </td>
              <td>
                <%= student.rank  %>
              </td>
            </td>
            <% end %>
            <% end %>
            <% if @num == 0 %>
            <tr>
              <td>なし</td>
            </tr>
            <% end %>
          </table>
          <%if current_user.id == 1%>
          <%= link_to 'Show', lab %>
          <%= link_to 'Edit', edit_lab_path(lab) %>
          <%= link_to 'Destroy', lab, method: :delete, data: { confirm: 'Are you sure?' } %>
          <%end%>
        </div>
      </div>
      <% end %>
    </div>
    <hr>
    <div class="row">
      <h2>協力者</h2>
      <div class="code_list">
        <% @codes.each do |student| %>
        <div class="col-md-2 col-xs-3">
          <%= student.code %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <br>
  <%if current_user.id == 1%>
  <%= link_to 'New Lab', new_lab_path %>
  <% end %>
</div>

app/views/labs/new.html.erb
<h1>New Lab</h1>

<%= render 'form', lab: @lab %>

<%= link_to 'Back', labs_path %>

app/views/labs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lab.name %>
</p>

<p>
  <strong>Cap:</strong>
  <%= @lab.cap %>
</p>

<p>
  <strong>Info:</strong>
  <%= @lab.info %>
</p>

<%= link_to 'Edit', edit_lab_path(@lab) %> |
<%= link_to 'Back', labs_path %>